# Generated by Django 5.0.1 on 2024-01-22 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='companydetails',
            name='email',
            field=models.EmailField(max_length=255, null=True),
        ),
    ]
