# Generated by Django 5.0.1 on 2024-01-22 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_companydetails_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='companydashboard',
            name='active',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AddField(
            model_name='companydashboard',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='companydashboard',
            name='is_completed',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='companydashboard',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
