# Generated by Django 5.0.1 on 2024-01-22 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_companydashboard_active_companydashboard_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='packages',
            name='is_accepted',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AddField(
            model_name='packages',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
