# Generated by Django 5.0.1 on 2024-01-17 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('input_forms', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinformation',
            old_name='martial_status',
            new_name='marital_status',
        ),
    ]
