# Generated by Django 5.0.1 on 2024-01-16 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('input_forms', '0002_rename_hash_key_userinformation_case_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='ai_suggested',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
