# Generated by Django 5.0.1 on 2024-01-22 09:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("input_forms", "0002_rename_martial_status_userinformation_marital_status"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Budget",
        ),
    ]
