# Generated by Django 5.0.1 on 2024-01-16 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('input_forms', '0003_budget_ai_suggested'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='budget',
            table='bidding_data',
        ),
    ]
