# Generated by Django 3.2.10 on 2024-01-22 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyDashboard',
            fields=[
                ('case_id', models.CharField(default=1, max_length=255, primary_key=True, serialize=False, unique=True)),
                ('age', models.IntegerField(blank=True, max_length=255, null=True)),
                ('gender', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('bmi', models.FloatField(default=25, max_length=255, null=True)),
                ('children', models.IntegerField(blank=True, default=0, max_length=255, null=True)),
                ('smoker', models.BooleanField(default=False)),
                ('region', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('marital_status', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('income', models.BigIntegerField(default=0, max_length=255, null=True)),
                ('education', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('employment_status', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('recommended_value', models.IntegerField(blank=True, default='', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_completed', models.BooleanField(default=False, null=True)),
                ('active', models.BooleanField(default=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CompanyDetails',
            fields=[
                ('company_id', models.AutoField(default=0, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('email', models.EmailField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Packages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, max_length=255, null=True)),
                ('total_annual_coverage', models.IntegerField(blank=True, max_length=255, null=True)),
                ('accidental_emergencies', models.IntegerField(blank=True, max_length=255, null=True)),
                ('ambulance_services_expenses', models.IntegerField(blank=True, max_length=255, null=True)),
                ('hospitalization_room_charges', models.IntegerField(blank=True, max_length=255, null=True)),
                ('surgery', models.IntegerField(blank=True, max_length=255, null=True)),
                ('dental_and_vision_care', models.IntegerField(blank=True, max_length=255, null=True)),
                ('other_medical_expenses', models.IntegerField(blank=True, max_length=255, null=True)),
                ('company_bid', models.IntegerField(blank=True, default=0, max_length=255, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_accepted', models.BooleanField(default=True, null=True)),
                ('case_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='dashboard.companydashboard')),
                ('company_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.companydetails')),
            ],
        ),
    ]
