# Generated by Django 3.2.10 on 2024-01-24 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyDashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_id', models.CharField(default=1, max_length=255, unique=True)),
                ('age', models.IntegerField(blank=True, max_length=255, null=True)),
                ('gender', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('bmi', models.FloatField(default=25, max_length=255, null=True)),
                ('children', models.IntegerField(blank=True, default=0, max_length=255, null=True)),
                ('smoker', models.BooleanField(default=False)),
                ('region', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('marital_status', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('income', models.BigIntegerField(default=0, max_length=255, null=True)),
                ('education', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('employment_status', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('recommended_value', models.IntegerField(blank=True, default='', max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CompanyPackages',
            fields=[
                ('id', models.AutoField(default=0, primary_key=True, serialize=False)),
                ('case_id', models.CharField(default=1, max_length=255)),
                ('company_name', models.CharField(blank=True, max_length=255, null=True)),
                ('total_annual_coverage', models.IntegerField(blank=True, max_length=255, null=True)),
                ('accidental_emergencies', models.IntegerField(blank=True, max_length=255, null=True)),
                ('ambulance_services_expenses', models.IntegerField(blank=True, max_length=255, null=True)),
                ('hospitalization_room_charges', models.IntegerField(blank=True, max_length=255, null=True)),
                ('surgery', models.IntegerField(blank=True, max_length=255, null=True)),
                ('dental_and_vision_care', models.IntegerField(blank=True, max_length=255, null=True)),
                ('other_medical_expenses', models.IntegerField(blank=True, max_length=255, null=True)),
                ('company_bid', models.IntegerField(blank=True, default=0, max_length=255, null=True)),
            ],
        ),
    ]
