# Generated by Django 5.0.1 on 2024-01-17 20:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyPackages',
            fields=[
                ('package_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='dashboard.companydashboard')),
                ('case_id', models.CharField(default=1, max_length=255, unique=True)),
                ('company_name', models.CharField(blank=True, max_length=255, null=True)),
                ('total_annual_coverage', models.IntegerField(blank=True, max_length=255, null=True)),
                ('accidental_emergencies', models.IntegerField(blank=True, max_length=255, null=True)),
                ('ambulance_services_expenses', models.IntegerField(blank=True, max_length=255, null=True)),
                ('hospitalization_room_charges', models.IntegerField(blank=True, max_length=255, null=True)),
                ('surgery', models.IntegerField(blank=True, max_length=255, null=True)),
                ('dental_and_vision_care', models.IntegerField(blank=True, max_length=255, null=True)),
                ('other_medical_expenses', models.IntegerField(blank=True, max_length=255, null=True)),
                ('company_bid', models.IntegerField(blank=True, default=0, max_length=255, null=True)),
            ],
        ),
    ]
