# Generated by Django 5.0.1 on 2024-01-13 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyDashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_id', models.IntegerField(default=1, max_length=255, unique=True)),
                ('age', models.IntegerField(blank=True, max_length=255, null=True)),
                ('gender', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('bmi', models.FloatField(default=25, max_length=255, null=True)),
                ('children', models.IntegerField(blank=True, default=0, max_length=255, null=True)),
                ('smoker', models.BooleanField(default=False)),
                ('region', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('marital_status', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('income', models.BigIntegerField(default=0, max_length=255, null=True)),
                ('education', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('employment_status', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('recommended_value', models.IntegerField(blank=True, default='', max_length=255, null=True)),
            ],
        ),
    ]
